version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.22.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run lint
      - run: yarn lint
      # run tests!
      - run: yarn test --runInBand --logHeapUsage && ./node_modules/.bin/codecov
      # deploy storybook
      - run: yarn chromatic --project-token=c6317a751fef --auto-accept-changes
