export const Roles = {
  button: 'button',
  combobox: 'combobox',
  error: 'error',
  formInput: 'form-input',
  formRadio: 'radio',
  formCheckbox: 'checkbox',
  formGroup: 'form-group',
  listbox: 'listbox',
  listItem: 'listitem',
  list: 'list',
  prefix: 'prefix',
  presentation: 'presentation',
  progress: 'progress',
  region: 'region',
  suffix: 'suffix',
  tab: 'tab',
  tablist: 'tablist',
  tabpanel: 'tabpanel',
  textbox: 'textbox',
  toggle: 'form-toggle',
};
